import type { Data } from '@measured/puck'
import type { StoreTemplate } from '@/types/templates'

// ─────────────────────────────────────────────────────────────────────────────
// TIER 1  ▸  Fashion & Apparel  ($957B market)
// Brand:  LUXE  |  Dark editorial, luxury fashion store
// ─────────────────────────────────────────────────────────────────────────────
const fashionPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-fashion-hdr',
        logoUrl: '',
        logoAlt: 'LUXE',
        backgroundColor: '#0a0a0a',
        textColor: '#f5f5f0',
        sticky: true,
        navLinks: [
          { label: 'New Arrivals', url: '/new' },
          { label: 'Collections',  url: '/collections' },
          { label: 'Sale',         url: '/sale' },
          { label: 'About',        url: '/about' },
        ],
      },
    },
    {
      type: 'HeroBanner',
      props: {
        id: 'HeroBanner-fashion-hero',
        headline: 'Wear Your Story',
        subheadline: 'Curated fashion for the bold and the beautiful. New collection — now live.',
        buttonText: 'Shop the Collection',
        buttonUrl: '/collections',
        buttonColor: '#c9a96e',
        backgroundImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=80',
        overlayOpacity: 45,
        textAlign: 'center',
        minHeight: 600,
      },
    },
    {
      type: 'CollectionList',
      props: {
        id: 'CollectionList-fashion-cats',
        headline: 'Shop by Collection',
        columns: 4,
        backgroundColor: '#ffffff',
        collections: [
          { name: 'New Arrivals',  imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=400&q=80', url: '/collections/new' },
          { name: 'Workwear',      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80', url: '/collections/workwear' },
          { name: 'Casuals',       imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=400&q=80', url: '/collections/casuals' },
          { name: 'Sale',          imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=400&q=80', url: '/collections/sale' },
        ],
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-fashion-promise',
        headline: 'The LUXE Promise',
        subheadline: 'Every piece is chosen with intention.',
        columns: 4,
        cardStyle: 'icon-top',
        accentColor: '#c9a96e',
        backgroundColor: '#fafaf8',
        textColor: '#1a1a1a',
        items: [
          { icon: '🚚', title: 'Free Delivery',    description: 'Free shipping on all orders over R 800.' },
          { icon: '↩️', title: 'Easy Returns',     description: '30-day hassle-free returns on all items.' },
          { icon: '✦',  title: 'Premium Quality',  description: 'Ethically sourced, handpicked fabrics.' },
          { icon: '🔒', title: 'Secure Checkout',  description: 'SSL-encrypted payments, always safe.' },
        ],
      },
    },
    {
      type: 'ProductShowcase',
      props: {
        id: 'ProductShowcase-fashion-new',
        headline: 'New Arrivals',
        subheadline: 'This season\'s most-wanted pieces.',
        columns: 4,
        count: 8,
        cardStyle: 'minimal',
        imageAspectRatio: '3/4',
        showBadge: true,
        badgeText: 'NEW',
        badgeColor: '#c9a96e',
        showRating: false,
        showWishlist: true,
        showSalePrice: false,
        accentColor: '#0a0a0a',
        backgroundColor: '#ffffff',
        textColor: '#0a0a0a',
        cardRadius: 4,
        gap: 16,
        categorySlug: 'new-arrivals',
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-fashion-reviews',
        headline: 'Loved by Our Community',
        subheadline: 'Real stories from real customers.',
        columns: 3,
        backgroundColor: '#fafaf8',
        cardColor: '#ffffff',
        textColor: '#1a1a1a',
        accentColor: '#c9a96e',
        items: [
          { quote: "The quality is exceptional — I've never felt more confident walking into a room. Worth every cent.", authorName: 'Ayesha Patel',    authorRole: 'Cape Town',    authorAvatar: '', rating: 5 },
          { quote: 'I ordered on Tuesday and received my parcel on Thursday. The packaging was beautiful too!',          authorName: 'Lerato Dlamini',  authorRole: 'Johannesburg', authorAvatar: '', rating: 5 },
          { quote: 'Finally a local brand that understands fit and style. The linen collection is stunning.',            authorName: 'Sam van der Berg', authorRole: 'Stellenbosch', authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'NewsletterSignup',
      props: {
        id: 'NewsletterSignup-fashion-nl',
        layout: 'banner',
        showFirstName: false,
        headline: 'Join the Inner Circle',
        subheadline: 'Be first to know about new drops, exclusive offers, and styling tips.',
        placeholder: 'Your email address',
        buttonText: 'Subscribe',
        privacyText: 'No spam, ever. Unsubscribe at any time.',
        successMessage: 'Welcome to the inner circle!',
        webhookUrl: '',
        accentColor: '#c9a96e',
        backgroundColor: '#f5f5f0',
        textColor: '#1a1a1a',
        borderRadius: 8,
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-fashion-ftr',
        copyrightText: '© 2025 LUXE Fashion. All rights reserved.',
        backgroundColor: '#0a0a0a',
        textColor: '#666666',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// TIER 1  ▸  Consumer Electronics  ($976B market)
// Brand:  TechVault  |  Spec-forward, comparison-driven tech store
// ─────────────────────────────────────────────────────────────────────────────
const electronicsPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-elec-hdr',
        logoUrl: '',
        logoAlt: 'TechVault',
        backgroundColor: '#0f172a',
        textColor: '#e2e8f0',
        sticky: true,
        navLinks: [
          { label: 'Laptops',     url: '/laptops' },
          { label: 'Smartphones', url: '/phones' },
          { label: 'Audio',       url: '/audio' },
          { label: 'Deals',       url: '/deals' },
        ],
      },
    },
    {
      type: 'HeroSection',
      props: {
        id: 'HeroSection-elec-hero',
        eyebrow: 'New Arrivals 2025',
        headline: 'Tech That Moves You Forward',
        subheadline: 'From cutting-edge laptops to premium audio — find the gear that powers your world.',
        primaryButtonText: 'Shop Now',
        primaryButtonUrl: '/shop',
        primaryButtonColor: '#6366f1',
        secondaryButtonText: 'View Deals',
        secondaryButtonUrl: '/deals',
        backgroundImage: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1600&q=80',
        backgroundColor: '#0f172a',
        overlayOpacity: 60,
        textAlign: 'center',
        minHeight: 580,
      },
    },
    {
      type: 'ProductCarousel',
      props: {
        id: 'ProductCarousel-elec-trending',
        headline: 'Trending This Week',
        subheadline: 'Our most-loved tech picks right now.',
        viewAllText: 'View All',
        viewAllUrl: '/shop',
        count: 8,
        cardWidth: 240,
        showArrows: true,
        showBadge: true,
        badgeText: 'HOT',
        badgeColor: '#ef4444',
        showRating: true,
        accentColor: '#6366f1',
        backgroundColor: '#ffffff',
        textColor: '#0f172a',
        cardRadius: 12,
        categorySlug: '',
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-elec-specs',
        headline: 'Why TechVault',
        subheadline: 'The complete electronics experience — purchase to aftercare.',
        columns: 4,
        cardStyle: 'boxed',
        accentColor: '#6366f1',
        backgroundColor: '#f8fafc',
        textColor: '#0f172a',
        items: [
          { icon: '🛡️', title: '2-Year Warranty',   description: 'All products covered for 2 years with local support.' },
          { icon: '⚡',  title: 'Same-Day Delivery', description: 'Order before 2pm — delivered to your door today.' },
          { icon: '🔧', title: 'Expert Setup',       description: 'Technicians configure your device remotely, free.' },
          { icon: '♻️', title: 'Trade-In',           description: 'Get up to R 5,000 credit on your old device.' },
        ],
      },
    },
    {
      type: 'ProductShowcase',
      props: {
        id: 'ProductShowcase-elec-featured',
        headline: 'Editor\'s Picks',
        subheadline: 'Curated by our tech experts this month.',
        columns: 4,
        count: 8,
        cardStyle: 'classic',
        imageAspectRatio: '1/1',
        showBadge: true,
        badgeText: 'TOP RATED',
        badgeColor: '#6366f1',
        showRating: true,
        showWishlist: true,
        showSalePrice: true,
        accentColor: '#6366f1',
        backgroundColor: '#ffffff',
        textColor: '#0f172a',
        cardRadius: 12,
        gap: 20,
        categorySlug: '',
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-elec-reviews',
        headline: 'Trusted by Tech Lovers',
        subheadline: 'See what our customers are saying.',
        columns: 3,
        backgroundColor: '#ffffff',
        cardColor: '#f8fafc',
        textColor: '#0f172a',
        accentColor: '#f59e0b',
        items: [
          { quote: 'Got my laptop within 4 hours of ordering. The setup service was incredible.',       authorName: 'Thabo Molefe',   authorRole: 'Software Engineer',  authorAvatar: '', rating: 5 },
          { quote: 'The trade-in value I got for my old phone was far better than anywhere else.',      authorName: 'Nina Okafor',    authorRole: 'Marketing Manager', authorAvatar: '', rating: 5 },
          { quote: 'Excellent warranty support — replaced my screen within 24 hours, no questions.',   authorName: 'Jaco Pretorius', authorRole: 'Graphic Designer',  authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'CallToAction',
      props: {
        id: 'CallToAction-elec-tradein',
        headline: 'Upgrade Today — Trade In Your Old Device',
        subheadline: 'Get up to R 5,000 credit when you trade in your phone, laptop, or tablet.',
        primaryButtonText: 'Check Trade-In Value',
        primaryButtonUrl: '/trade-in',
        primaryButtonColor: '#ffffff',
        secondaryButtonText: 'Browse All Products',
        secondaryButtonUrl: '/shop',
        backgroundImage: '',
        backgroundColor: '#6366f1',
        overlayOpacity: 55,
        textColor: '#ffffff',
        paddingY: 80,
      },
    },
    {
      type: 'NewsletterSignup',
      props: {
        id: 'NewsletterSignup-elec-nl',
        layout: 'minimal',
        showFirstName: false,
        headline: 'Stay Ahead of the Curve',
        subheadline: 'Tech news, deals, and drops — straight to your inbox.',
        placeholder: 'Enter your email',
        buttonText: 'Subscribe',
        privacyText: 'Unsubscribe anytime.',
        successMessage: "You're in! Watch your inbox.",
        webhookUrl: '',
        accentColor: '#6366f1',
        backgroundColor: '#f8fafc',
        textColor: '#0f172a',
        borderRadius: 8,
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-elec-ftr',
        copyrightText: '© 2025 TechVault. All rights reserved.',
        backgroundColor: '#0f172a',
        textColor: '#64748b',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// TIER 1  ▸  Health & Beauty  (high-margin, repeat-purchase)
// Brand:  GlowLab  |  Clean beauty, science-backed skincare
// ─────────────────────────────────────────────────────────────────────────────
const beautyPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-beauty-hdr',
        logoUrl: '',
        logoAlt: 'GlowLab',
        backgroundColor: '#ffffff',
        textColor: '#3d2b1f',
        sticky: true,
        navLinks: [
          { label: 'Skincare',  url: '/skincare' },
          { label: 'Body',      url: '/body' },
          { label: 'Haircare',  url: '/haircare' },
          { label: 'Bundles',   url: '/bundles' },
        ],
      },
    },
    {
      type: 'HeroBanner',
      props: {
        id: 'HeroBanner-beauty-hero',
        headline: 'Science Meets Skin',
        subheadline: 'Clinically tested, plant-powered formulas designed for real results. No compromise.',
        buttonText: 'Shop Bestsellers',
        buttonUrl: '/bestsellers',
        buttonColor: '#d4846a',
        backgroundImage: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=1600&q=80',
        overlayOpacity: 30,
        textAlign: 'center',
        minHeight: 560,
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-beauty-claims',
        headline: 'The GlowLab Difference',
        subheadline: 'Every formula earns its place on your skin.',
        columns: 4,
        cardStyle: 'icon-top',
        accentColor: '#d4846a',
        backgroundColor: '#fdf8f5',
        textColor: '#3d2b1f',
        items: [
          { icon: '🌿', title: 'Clean Ingredients',      description: 'Free from parabens, sulphates, and synthetic fragrance.' },
          { icon: '🐰', title: 'Cruelty-Free',           description: 'Certified cruelty-free. Never tested on animals.' },
          { icon: '🧪', title: 'Dermatologist Tested',   description: 'Tested and approved by certified dermatologists.' },
          { icon: '♻️', title: 'Sustainable Packaging',  description: 'Recyclable packaging with refill options available.' },
        ],
      },
    },
    {
      type: 'ProductShowcase',
      props: {
        id: 'ProductShowcase-beauty-bestsellers',
        headline: 'Bestsellers',
        subheadline: 'The formulas our community keeps coming back for.',
        columns: 4,
        count: 8,
        cardStyle: 'classic',
        imageAspectRatio: '3/4',
        showBadge: true,
        badgeText: 'BESTSELLER',
        badgeColor: '#d4846a',
        showRating: true,
        showWishlist: true,
        showSalePrice: false,
        accentColor: '#d4846a',
        backgroundColor: '#ffffff',
        textColor: '#3d2b1f',
        cardRadius: 16,
        gap: 20,
        categorySlug: 'bestsellers',
      },
    },
    {
      type: 'CallToAction',
      props: {
        id: 'CallToAction-beauty-quiz',
        headline: 'Not Sure Where to Start?',
        subheadline: 'Take our 60-second skin quiz and get a personalised routine recommendation — free.',
        primaryButtonText: 'Take the Skin Quiz',
        primaryButtonUrl: '/quiz',
        primaryButtonColor: '#d4846a',
        secondaryButtonText: 'View All Products',
        secondaryButtonUrl: '/products',
        backgroundImage: '',
        backgroundColor: '#fdf3ef',
        overlayOpacity: 0,
        textColor: '#3d2b1f',
        paddingY: 72,
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-beauty-results',
        headline: 'Real Results, Real People',
        subheadline: 'We let the skin speak for itself.',
        columns: 3,
        backgroundColor: '#ffffff',
        cardColor: '#fdf8f5',
        textColor: '#3d2b1f',
        accentColor: '#d4846a',
        items: [
          { quote: 'After 3 weeks my skin was visibly clearer. The Vitamin C serum is now a non-negotiable in my routine.',  authorName: 'Zanele Mokoena',  authorRole: 'Cape Town',    authorAvatar: '', rating: 5 },
          { quote: 'I have sensitive skin and finally found products that don\'t cause a reaction. Completely obsessed.',     authorName: 'Priya Naidoo',    authorRole: 'Durban',       authorAvatar: '', rating: 5 },
          { quote: 'My esthetician actually asked what I was using — that\'s when I knew GlowLab was different.',            authorName: 'Claudette Fourie', authorRole: 'Pretoria',    authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'FAQAccordion',
      props: {
        id: 'FAQAccordion-beauty-faq',
        headline: 'Common Questions',
        subheadline: '',
        backgroundColor: '#fdf8f5',
        cardColor: '#ffffff',
        textColor: '#3d2b1f',
        accentColor: '#d4846a',
        maxWidth: 720,
        items: [
          { question: 'Are your products suitable for sensitive skin?',       answer: 'Yes — all GlowLab formulas are dermatologist-tested and free from common irritants. For extremely reactive skin, patch-test on your inner arm first.' },
          { question: 'What is your return policy?',                          answer: 'We offer a 30-day satisfaction guarantee. If your skin doesn\'t love it, contact us for a full refund — no return needed for opened products.' },
          { question: 'Do you offer a subscription or bundle discount?',      answer: 'Yes! Subscribe & Save gives you 15% off every order, free shipping, and early access to new launches. Cancel or pause anytime.' },
          { question: 'Which products should I start with?',                  answer: 'Take our free skin quiz for a personalised recommendation, or start with The Starter Trio — our most popular cleanser, serum, and moisturiser bundle.' },
          { question: 'How long until I see results?',                        answer: 'Most customers see visible improvement within 2–4 weeks. Pigmentation and deeper concerns typically show results after 8–12 weeks of consistent use.' },
        ],
      },
    },
    {
      type: 'NewsletterSignup',
      props: {
        id: 'NewsletterSignup-beauty-nl',
        layout: 'card',
        showFirstName: true,
        headline: 'Get 10% Off Your First Order',
        subheadline: 'Plus exclusive skincare tips and early access to new products.',
        placeholder: 'Your email address',
        buttonText: 'Claim Your Discount',
        privacyText: 'Unsubscribe anytime. We respect your inbox.',
        successMessage: 'Your discount code is on its way!',
        webhookUrl: '',
        accentColor: '#d4846a',
        backgroundColor: '#ffffff',
        textColor: '#3d2b1f',
        borderRadius: 16,
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-beauty-ftr',
        copyrightText: '© 2025 GlowLab. All rights reserved. Cruelty-free & proudly South African.',
        backgroundColor: '#3d2b1f',
        textColor: '#a89080',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// TIER 2  ▸  Food & Beverage DTC  (9.4% CAGR, subscription-heavy)
// Brand:  FreshBox  |  Weekly farm-to-table ingredient subscription
// ─────────────────────────────────────────────────────────────────────────────
const foodBevPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-food-hdr',
        logoUrl: '',
        logoAlt: 'FreshBox',
        backgroundColor: '#1a3a2a',
        textColor: '#f0ece4',
        sticky: true,
        navLinks: [
          { label: 'How It Works', url: '/how-it-works' },
          { label: 'This Week',    url: '/menu' },
          { label: 'Recipes',      url: '/recipes' },
          { label: 'Pricing',      url: '/pricing' },
        ],
      },
    },
    {
      type: 'HeroSection',
      props: {
        id: 'HeroSection-food-hero',
        eyebrow: 'Farm to Doorstep',
        headline: 'Eat Better, Every Single Week',
        subheadline: 'Hand-picked seasonal ingredients and chef-crafted recipes delivered to your door. No planning required.',
        primaryButtonText: 'Start My First Box',
        primaryButtonUrl: '/subscribe',
        primaryButtonColor: '#4a9e6b',
        secondaryButtonText: 'See This Week\'s Menu',
        secondaryButtonUrl: '/menu',
        backgroundImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1600&q=80',
        backgroundColor: '#1a3a2a',
        overlayOpacity: 45,
        textAlign: 'center',
        minHeight: 600,
      },
    },
    {
      type: 'CountdownTimer',
      props: {
        id: 'CountdownTimer-food-cutoff',
        headline: 'Order Before Wednesday Midnight',
        subheadline: 'Get your box delivered this Friday. Miss the cutoff and we\'ll see you next week.',
        targetDate: '2026-01-28T23:59:59',
        endMessage: '🚜 This week\'s orders are in! Next box ships Friday.',
        showDays: true,
        showHours: true,
        showMinutes: true,
        showSeconds: false,
        cardStyle: 'card',
        accentColor: '#4a9e6b',
        backgroundColor: '#f0ece4',
        cardColor: '#ffffff',
        textColor: '#1a3a2a',
        labelColor: '#6b7280',
        primaryButtonText: 'Subscribe Now',
        primaryButtonUrl: '/subscribe',
      },
    },
    {
      type: 'PricingTable',
      props: {
        id: 'PricingTable-food-plans',
        headline: 'Choose Your Box Size',
        subheadline: 'Pause, skip, or cancel anytime — no contracts, no commitments.',
        backgroundColor: '#ffffff',
        textColor: '#1a3a2a',
        plans: [
          {
            name: 'Solo Box',
            price: 'R 349',
            period: '/ week',
            description: 'Perfect for 1–2 people. 3 recipes, 2 servings each.',
            features: '3 recipes per week\n2 servings each\nSeasonal fresh ingredients\nFull recipe cards\nSkip or pause anytime',
            highlighted: false,
            highlightColor: '#6b7280',
            buttonText: 'Start Solo Box',
            buttonUrl: '/subscribe/solo',
          },
          {
            name: 'Family Box',
            price: 'R 649',
            period: '/ week',
            description: 'For families of 4. 4 recipes, 4 servings each.',
            features: '4 recipes per week\n4 servings each\nKid-friendly options\nSeasonal fresh ingredients\nFull recipe cards\nSkip or pause anytime',
            highlighted: true,
            highlightColor: '#4a9e6b',
            buttonText: 'Start Family Box',
            buttonUrl: '/subscribe/family',
          },
          {
            name: 'Chef\'s Box',
            price: 'R 899',
            period: '/ week',
            description: 'Premium cuts, rare produce, and advanced recipes.',
            features: '4 premium recipes\n4 servings each\nPremium & rare ingredients\nWine pairing guide\nChef video tutorials\nFree delivery always',
            highlighted: false,
            highlightColor: '#1a3a2a',
            buttonText: 'Start Chef\'s Box',
            buttonUrl: '/subscribe/chef',
          },
        ],
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-food-why',
        headline: 'Why FreshBox?',
        subheadline: 'We handle the planning, you handle the eating.',
        columns: 4,
        cardStyle: 'minimal',
        accentColor: '#4a9e6b',
        backgroundColor: '#f0ece4',
        textColor: '#1a3a2a',
        items: [
          { icon: '🌾', title: 'Sourced Fresh Daily',      description: 'Ingredients picked and packed within 24 hours of delivery.' },
          { icon: '📋', title: 'Recipe Cards Included',    description: 'Step-by-step cards with prep times under 35 minutes.' },
          { icon: '⏸️', title: 'Skip Any Week',            description: 'Going away? Skip or pause with one click, anytime.' },
          { icon: '🌱', title: 'Seasonal & Sustainable',   description: 'We source from local farms to reduce food miles and waste.' },
        ],
      },
    },
    {
      type: 'ProductGrid',
      props: {
        id: 'ProductGrid-food-items',
        headline: "This Week's Featured Ingredients",
        columns: 4,
        rows: 1,
        categorySlug: 'this-week',
        showPlaceholder: true,
        backgroundColor: '#ffffff',
        gap: 20,
      },
    },
    {
      type: 'BlogPostList',
      props: {
        id: 'BlogPostList-food-recipes',
        headline: 'From Our Kitchen',
        subheadline: 'Recipes, stories, and seasonal inspiration.',
        layout: 'grid',
        columns: 3,
        showAuthor: true,
        showDate: true,
        showCategory: true,
        showExcerpt: true,
        readMoreText: 'Read recipe',
        accentColor: '#4a9e6b',
        backgroundColor: '#f0ece4',
        cardColor: '#ffffff',
        textColor: '#1a3a2a',
        borderRadius: 12,
        posts: [
          { title: 'Butternut & Sage Gnocchi',           excerpt: 'A deeply satisfying autumn dish ready in 30 minutes. The brown butter sage sauce is the secret.', thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=400&q=80', date: '15 Jan 2025', author: 'Chef Nina', category: 'Recipe',   url: '/recipes/gnocchi' },
          { title: 'Grilling Season: 5 Marinades',       excerpt: 'Keep your braai interesting all summer with these five crowd-pleasing marinades.', thumbnail: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=400&q=80', date: '8 Jan 2025',  author: 'The Team',  category: 'Seasonal', url: '/recipes/marinades' },
          { title: 'How to Reduce Food Waste at Home',   excerpt: 'Simple strategies that\'ll save you money and help the planet — starting with what\'s in your fridge.', thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=400&q=80', date: '2 Jan 2025',  author: 'Chef Nina', category: 'Tips',     url: '/blog/food-waste' },
        ],
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-food-love',
        headline: 'What Our Members Say',
        subheadline: 'Thousands of happy kitchens and counting.',
        columns: 3,
        backgroundColor: '#ffffff',
        cardColor: '#f0ece4',
        textColor: '#1a3a2a',
        accentColor: '#4a9e6b',
        items: [
          { quote: 'We used to order takeout 4 nights a week. Now we actually cook together and it\'s become our favourite part of the day.', authorName: 'The Joubert Family', authorRole: 'Johannesburg',  authorAvatar: '', rating: 5 },
          { quote: 'The ingredients are genuinely fresh — you can taste the difference. I\'ve stopped wasting food completely.',             authorName: 'Taryn Hendricks',   authorRole: 'Cape Town',     authorAvatar: '', rating: 5 },
          { quote: 'Chef\'s Box introduced me to ingredients I\'d never heard of. My cooking skills have genuinely improved.',              authorName: 'Sipho Dlamini',      authorRole: 'Durban',        authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'FAQAccordion',
      props: {
        id: 'FAQAccordion-food-faq',
        headline: 'Common Questions',
        subheadline: '',
        backgroundColor: '#f0ece4',
        cardColor: '#ffffff',
        textColor: '#1a3a2a',
        accentColor: '#4a9e6b',
        maxWidth: 720,
        items: [
          { question: 'How does the subscription work?',              answer: 'Subscribe and choose your box size. Each week you\'ll receive fresh ingredients + recipe cards. You can log in any time to skip a week, pause, or change your box size.' },
          { question: 'Can I skip a delivery?',                       answer: 'Yes! Log in and skip any upcoming delivery before Wednesday midnight. Skipping a week is instant and there are no fees or limits.' },
          { question: 'Do you cater for dietary requirements?',       answer: 'We offer vegetarian, pescatarian, and low-carb filter options. Vegan and gluten-free boxes are coming soon. You can set your preferences in your account.' },
          { question: 'What areas do you deliver to?',               answer: 'We currently deliver to Cape Town, Johannesburg, Durban, Pretoria, and Port Elizabeth. We\'re expanding fast — enter your postcode to check availability.' },
          { question: 'What if I\'m not home for the delivery?',     answer: 'Our boxes are insulated with eco-ice packs to stay fresh for 8+ hours. We\'ll leave it at your door with delivery instructions you specify at checkout.' },
        ],
      },
    },
    {
      type: 'NewsletterSignup',
      props: {
        id: 'NewsletterSignup-food-nl',
        layout: 'banner',
        showFirstName: true,
        headline: 'Get Your First Box for 50% Off',
        subheadline: 'Join 12,000+ households cooking fresh with FreshBox.',
        placeholder: 'Email address',
        buttonText: 'Claim 50% Off',
        privacyText: 'Offer for new subscribers only. Unsubscribe anytime.',
        successMessage: 'Your discount is in your inbox!',
        webhookUrl: '',
        accentColor: '#4a9e6b',
        backgroundColor: '#1a3a2a',
        textColor: '#f0ece4',
        borderRadius: 8,
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-food-ftr',
        copyrightText: '© 2025 FreshBox. Farm to doorstep across South Africa.',
        backgroundColor: '#1a3a2a',
        textColor: '#6b9e7b',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// TIER 2  ▸  Pet Supplies  (loyal customer base, recurring revenue)
// Brand:  PawHQ  |  Premium pet food, accessories, and wellness
// ─────────────────────────────────────────────────────────────────────────────
const petSuppliesPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-pet-hdr',
        logoUrl: '',
        logoAlt: 'PawHQ',
        backgroundColor: '#ffffff',
        textColor: '#1c1917',
        sticky: true,
        navLinks: [
          { label: 'Dogs',         url: '/dogs' },
          { label: 'Cats',         url: '/cats' },
          { label: 'Small Pets',   url: '/small-pets' },
          { label: 'Subscribe & Save', url: '/subscribe' },
        ],
      },
    },
    {
      type: 'HeroBanner',
      props: {
        id: 'HeroBanner-pet-hero',
        headline: 'Because They Deserve the Best',
        subheadline: 'Premium pet food, toys, and wellness products — vet formulated and pet approved.',
        buttonText: 'Shop for My Pet',
        buttonUrl: '/shop',
        buttonColor: '#f97316',
        backgroundImage: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1600&q=80',
        overlayOpacity: 35,
        textAlign: 'left',
        minHeight: 560,
      },
    },
    {
      type: 'CollectionList',
      props: {
        id: 'CollectionList-pet-species',
        headline: 'Shop by Pet',
        columns: 4,
        backgroundColor: '#fff7ed',
        collections: [
          { name: '🐶 Dogs',        imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=400&q=80', url: '/dogs' },
          { name: '🐱 Cats',        imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=400&q=80', url: '/cats' },
          { name: '🐹 Small Pets',  imageUrl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=400&q=80', url: '/small-pets' },
          { name: '🐦 Birds',       imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=400&q=80', url: '/birds' },
        ],
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-pet-trust',
        headline: 'The PawHQ Standard',
        subheadline: 'We hold every product to the same standards we\'d set for our own pets.',
        columns: 4,
        cardStyle: 'boxed',
        accentColor: '#f97316',
        backgroundColor: '#ffffff',
        textColor: '#1c1917',
        items: [
          { icon: '🩺', title: 'Vet Recommended',     description: 'Every product is reviewed and recommended by certified vets.' },
          { icon: '🌿', title: 'Natural Ingredients',  description: 'No artificial preservatives, colours, or fillers.' },
          { icon: '🚚', title: 'Free Delivery R 500+', description: 'Free nationwide delivery on all orders over R 500.' },
          { icon: '↩️', title: '30-Day Guarantee',    description: 'Your pet not happy? Return it within 30 days, no questions asked.' },
        ],
      },
    },
    {
      type: 'ProductCarousel',
      props: {
        id: 'ProductCarousel-pet-trending',
        headline: 'This Week\'s Top Picks',
        subheadline: 'What pet parents are buying right now.',
        viewAllText: 'View All',
        viewAllUrl: '/shop',
        count: 8,
        cardWidth: 220,
        showArrows: true,
        showBadge: true,
        badgeText: 'VET PICK',
        badgeColor: '#4ade80',
        showRating: true,
        accentColor: '#f97316',
        backgroundColor: '#fff7ed',
        textColor: '#1c1917',
        cardRadius: 12,
        categorySlug: '',
      },
    },
    {
      type: 'CallToAction',
      props: {
        id: 'CallToAction-pet-subscribe',
        headline: 'Subscribe & Save 20% on Every Order',
        subheadline: 'Never run out of your pet\'s favourite food again. Set your schedule and we\'ll handle the rest.',
        primaryButtonText: 'Set Up Auto-Delivery',
        primaryButtonUrl: '/subscribe',
        primaryButtonColor: '#ffffff',
        secondaryButtonText: 'Learn More',
        secondaryButtonUrl: '/subscribe',
        backgroundImage: '',
        backgroundColor: '#f97316',
        overlayOpacity: 0,
        textColor: '#ffffff',
        paddingY: 72,
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-pet-love',
        headline: 'Happy Pets, Happier Owners',
        subheadline: '',
        columns: 3,
        backgroundColor: '#ffffff',
        cardColor: '#fff7ed',
        textColor: '#1c1917',
        accentColor: '#f97316',
        items: [
          { quote: 'Switched my dog to PawHQ\'s grain-free range and his coat has never looked better. The vet noticed immediately!', authorName: 'Cindy Swanepoel',  authorRole: 'Cape Town', authorAvatar: '', rating: 5 },
          { quote: 'Auto-delivery is a game-changer. I never have to panic when I\'m running low on cat food anymore.',               authorName: 'Ruan van Tonder', authorRole: 'Pretoria',  authorAvatar: '', rating: 5 },
          { quote: 'My anxious rescue dog loves the calming chews. The difference in his behaviour within a week was remarkable.',    authorName: 'Kemi Adeyemi',    authorRole: 'Durban',    authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'FAQAccordion',
      props: {
        id: 'FAQAccordion-pet-faq',
        headline: 'Pet Parent FAQs',
        subheadline: '',
        backgroundColor: '#fff7ed',
        cardColor: '#ffffff',
        textColor: '#1c1917',
        accentColor: '#f97316',
        maxWidth: 720,
        items: [
          { question: 'How does the Subscribe & Save programme work?', answer: 'Choose any product, select your delivery frequency (every 2, 4, 6, or 8 weeks), and save 20% on every order. You can pause, skip, or cancel at any time from your account.' },
          { question: 'Are your foods suitable for all life stages?',  answer: 'We stock formulas for puppies/kittens, adults, and seniors. Each product page clearly indicates the life stage it\'s designed for. Our vet chat can help if you\'re unsure.' },
          { question: 'Do you offer a satisfaction guarantee?',       answer: 'Absolutely. If your pet doesn\'t love a product, return it within 30 days for a full refund or exchange — even if it\'s been opened and partially used.' },
          { question: 'How do I transition my pet to a new food?',    answer: 'We recommend a 7–10 day transition: mix 25% new food with 75% old food, gradually increasing the new food ratio each day. This prevents digestive upset.' },
        ],
      },
    },
    {
      type: 'NewsletterSignup',
      props: {
        id: 'NewsletterSignup-pet-nl',
        layout: 'banner',
        showFirstName: false,
        headline: 'Join 40,000 Pet Parents',
        subheadline: 'Get exclusive deals, vet tips, and product launches straight to your inbox.',
        placeholder: 'Your email address',
        buttonText: 'Join the Pack',
        privacyText: 'We respect your inbox. Unsubscribe anytime.',
        successMessage: 'Welcome to the pack! 🐾',
        webhookUrl: '',
        accentColor: '#f97316',
        backgroundColor: '#1c1917',
        textColor: '#f5f5f4',
        borderRadius: 8,
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-pet-ftr',
        copyrightText: '© 2025 PawHQ. Premium pet supplies, nationwide.',
        backgroundColor: '#1c1917',
        textColor: '#78716c',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// TIER 3  ▸  Home & Garden / Furniture  ($280B+ furniture market)
// Brand:  Habitat & Co.  |  Thoughtful furniture and home goods
// ─────────────────────────────────────────────────────────────────────────────
const homeGardenPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-home-hdr',
        logoUrl: '',
        logoAlt: 'Habitat & Co.',
        backgroundColor: '#f7f3ec',
        textColor: '#2c2416',
        sticky: true,
        navLinks: [
          { label: 'Living Room', url: '/living-room' },
          { label: 'Bedroom',     url: '/bedroom' },
          { label: 'Kitchen',     url: '/kitchen' },
          { label: 'Garden',      url: '/garden' },
        ],
      },
    },
    {
      type: 'HeroBanner',
      props: {
        id: 'HeroBanner-home-hero',
        headline: 'Spaces Worth Living In',
        subheadline: 'Solid wood furniture and home goods designed to last — made in South Africa.',
        buttonText: 'Explore the Collection',
        buttonUrl: '/shop',
        buttonColor: '#6b7c5a',
        backgroundImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1600&q=80',
        overlayOpacity: 25,
        textAlign: 'left',
        minHeight: 580,
      },
    },
    {
      type: 'CollectionList',
      props: {
        id: 'CollectionList-home-rooms',
        headline: 'Shop by Room',
        columns: 4,
        backgroundColor: '#ffffff',
        collections: [
          { name: 'Living Room', imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=400&q=80', url: '/living-room' },
          { name: 'Bedroom',     imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=400&q=80', url: '/bedroom' },
          { name: 'Kitchen',     imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=400&q=80', url: '/kitchen' },
          { name: 'Garden',      imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=400&q=80', url: '/garden' },
        ],
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-home-quality',
        headline: 'Crafted to Last',
        subheadline: 'We build to heirloom standard, not flat-pack standard.',
        columns: 4,
        cardStyle: 'minimal',
        accentColor: '#6b7c5a',
        backgroundColor: '#f7f3ec',
        textColor: '#2c2416',
        items: [
          { icon: '🪵', title: 'Solid Wood',         description: 'Kiln-dried hardwood sourced from certified South African suppliers.' },
          { icon: '🔧', title: 'Free Assembly',       description: 'Our team delivers and assembles in-room at no extra charge.' },
          { icon: '↩️', title: '100-Day Returns',    description: 'Live with it for 100 days. Not right for your space? We\'ll collect it.' },
          { icon: '✦',  title: '10-Year Guarantee',  description: 'Every piece comes with a 10-year structural guarantee.' },
        ],
      },
    },
    {
      type: 'ProductShowcase',
      props: {
        id: 'ProductShowcase-home-featured',
        headline: 'New This Season',
        subheadline: 'Pieces that change the way a room feels.',
        columns: 4,
        count: 8,
        cardStyle: 'overlay',
        imageAspectRatio: '4/3',
        showBadge: true,
        badgeText: 'NEW',
        badgeColor: '#6b7c5a',
        showRating: true,
        showWishlist: true,
        showSalePrice: false,
        accentColor: '#6b7c5a',
        backgroundColor: '#ffffff',
        textColor: '#2c2416',
        cardRadius: 8,
        gap: 16,
        categorySlug: 'new-season',
      },
    },
    {
      type: 'BlogPostList',
      props: {
        id: 'BlogPostList-home-styling',
        headline: 'Styling Inspiration',
        subheadline: 'Ideas for every room and every budget.',
        layout: 'featured',
        columns: 3,
        showAuthor: true,
        showDate: true,
        showCategory: true,
        showExcerpt: true,
        readMoreText: 'Read more',
        accentColor: '#6b7c5a',
        backgroundColor: '#f7f3ec',
        cardColor: '#ffffff',
        textColor: '#2c2416',
        borderRadius: 8,
        posts: [
          { title: 'The Case for a Statement Dining Table', excerpt: 'Why the dining table is the most important piece of furniture you\'ll ever buy — and how to choose the right one.', thumbnail: 'https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=600&q=80', date: '10 Jan 2025', author: 'Mila Roux',   category: 'Dining',  url: '/blog/dining-table' },
          { title: 'Coastal Calm: Our Newest Bedroom Range',  excerpt: 'Inspired by the South African coastline — natural textures, soft linens, and a palette built for rest.', thumbnail: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=400&q=80', date: '5 Jan 2025',  author: 'The Team', category: 'Bedroom', url: '/blog/coastal-bedroom' },
          { title: 'How to Style a Small Living Room',        excerpt: 'Six strategies that make any small space feel bigger, lighter, and infinitely more liveable.',               thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=400&q=80', date: '20 Dec 2024', author: 'Mila Roux',   category: 'Living',  url: '/blog/small-living-room' },
        ],
      },
    },
    {
      type: 'CallToAction',
      props: {
        id: 'CallToAction-home-consult',
        headline: 'Not Sure What\'ll Work in Your Space?',
        subheadline: 'Book a free 30-minute online design consultation with one of our home stylists.',
        primaryButtonText: 'Book a Free Consultation',
        primaryButtonUrl: '/consultation',
        primaryButtonColor: '#6b7c5a',
        secondaryButtonText: 'Browse Lookbooks',
        secondaryButtonUrl: '/lookbooks',
        backgroundImage: '',
        backgroundColor: '#f7f3ec',
        overlayOpacity: 0,
        textColor: '#2c2416',
        paddingY: 80,
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-home-customers',
        headline: 'Homes We\'ve Helped',
        subheadline: '',
        columns: 3,
        backgroundColor: '#ffffff',
        cardColor: '#f7f3ec',
        textColor: '#2c2416',
        accentColor: '#6b7c5a',
        items: [
          { quote: 'The delivery and assembly team were amazing. Two hours after they arrived, our whole living room was transformed.', authorName: 'Karla du Plessis',  authorRole: 'Cape Town',     authorAvatar: '', rating: 5 },
          { quote: 'We\'ve bought furniture from big retailers before and it never lasts. The oak dining table is built for life.',    authorName: 'Michael Ngubane',   authorRole: 'Johannesburg', authorAvatar: '', rating: 5 },
          { quote: 'I used the 100-day return once and it was genuinely effortless. No fuss, no questions — just collected.',         authorName: 'Hannelie Smit',     authorRole: 'Pretoria',     authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-home-ftr',
        copyrightText: '© 2025 Habitat & Co. Crafted with care in South Africa.',
        backgroundColor: '#2c2416',
        textColor: '#7a6a50',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// TIER 3  ▸  Jewelry & Accessories  (high visual requirements, detail views)
// Brand:  Aurum Jewels  |  Fine jewellery, gold, and certified diamonds
// ─────────────────────────────────────────────────────────────────────────────
const jewelryPuckState: Data = {
  root: { props: {} },
  content: [
    {
      type: 'SiteHeader',
      props: {
        id: 'SiteHeader-jewelry-hdr',
        logoUrl: '',
        logoAlt: 'AURUM',
        backgroundColor: '#0c0c0c',
        textColor: '#d4af7a',
        sticky: true,
        navLinks: [
          { label: 'Rings',      url: '/rings' },
          { label: 'Necklaces',  url: '/necklaces' },
          { label: 'Earrings',   url: '/earrings' },
          { label: 'Bracelets',  url: '/bracelets' },
        ],
      },
    },
    {
      type: 'HeroBanner',
      props: {
        id: 'HeroBanner-jewelry-hero',
        headline: 'Wear What Lasts Forever',
        subheadline: 'Hallmarked 18ct gold and certified diamonds. Handcrafted for moments worth remembering.',
        buttonText: 'Discover the Collection',
        buttonUrl: '/collections',
        buttonColor: '#d4af7a',
        backgroundImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1600&q=80',
        overlayOpacity: 50,
        textAlign: 'center',
        minHeight: 620,
      },
    },
    {
      type: 'CollectionList',
      props: {
        id: 'CollectionList-jewelry-types',
        headline: 'Shop by Category',
        columns: 4,
        backgroundColor: '#0c0c0c',
        collections: [
          { name: '💍 Rings',      imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80', url: '/rings' },
          { name: '📿 Necklaces',  imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=400&q=80', url: '/necklaces' },
          { name: '✦ Earrings',   imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=400&q=80', url: '/earrings' },
          { name: '⌚ Bracelets',  imageUrl: 'https://images.unsplash.com/photo-1573408301185-9519f94b6d48?auto=format&fit=crop&w=400&q=80', url: '/bracelets' },
        ],
      },
    },
    {
      type: 'ProductShowcase',
      props: {
        id: 'ProductShowcase-jewelry-collection',
        headline: 'The Signature Collection',
        subheadline: 'Pieces that carry meaning across generations.',
        columns: 5,
        count: 10,
        cardStyle: 'minimal',
        imageAspectRatio: '1/1',
        showBadge: false,
        badgeText: 'NEW',
        badgeColor: '#d4af7a',
        showRating: true,
        showWishlist: true,
        showSalePrice: false,
        accentColor: '#d4af7a',
        backgroundColor: '#f9f7f4',
        textColor: '#1a1714',
        cardRadius: 0,
        gap: 12,
        categorySlug: 'signature',
      },
    },
    {
      type: 'ImageGallery',
      props: {
        id: 'ImageGallery-jewelry-detail',
        headline: 'Craftsmanship Up Close',
        layout: 'grid',
        columns: 3,
        gap: 8,
        imageAspectRatio: '1/1',
        borderRadius: 0,
        showCaptions: true,
        overlayColor: 'rgba(212,175,122,0.25)',
        backgroundColor: '#0c0c0c',
        textColor: '#d4af7a',
        images: [
          { src: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80', alt: 'Solitaire Ring — 18ct White Gold', caption: 'Solitaire Diamond Ring — 18ct White Gold' },
          { src: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80', alt: 'Diamond Tennis Bracelet',           caption: 'Diamond Tennis Bracelet — 2.4ct Total' },
          { src: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80', alt: 'Layered Gold Necklaces',            caption: 'Heritage Layered Necklace Set — 18ct Yellow Gold' },
          { src: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80', alt: 'Drop Earrings',                     caption: 'Cascade Drop Earrings — Champagne Diamond' },
          { src: 'https://images.unsplash.com/photo-1573408301185-9519f94b6d48?auto=format&fit=crop&w=600&q=80', alt: 'Gold Bangle',                       caption: 'Classic Hammered Bangle — 18ct Gold' },
          { src: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80', alt: 'Engagement Ring Setting',            caption: 'Halo Engagement Ring — Platinum Setting' },
        ],
      },
    },
    {
      type: 'FeatureGrid',
      props: {
        id: 'FeatureGrid-jewelry-trust',
        headline: 'The Aurum Assurance',
        subheadline: 'Every piece we sell is exactly what we say it is.',
        columns: 4,
        cardStyle: 'boxed',
        accentColor: '#d4af7a',
        backgroundColor: '#f9f7f4',
        textColor: '#1a1714',
        items: [
          { icon: '🏅', title: 'Hallmarked Gold',      description: 'Every gold piece carries an official Assay Office hallmark.' },
          { icon: '💎', title: 'GIA Certified',         description: 'All diamonds come with a GIA or equivalent grading report.' },
          { icon: '🔒', title: 'Lifetime Warranty',     description: 'We stand behind our craftsmanship for the lifetime of the piece.' },
          { icon: '✍️', title: 'Free Engraving',        description: 'Personalise any ring or bracelet with a complimentary engraving.' },
        ],
      },
    },
    {
      type: 'Testimonials',
      props: {
        id: 'Testimonials-jewelry-love',
        headline: 'Moments Made Special',
        subheadline: '',
        columns: 3,
        backgroundColor: '#0c0c0c',
        cardColor: '#1a1714',
        textColor: '#f9f7f4',
        accentColor: '#d4af7a',
        items: [
          { quote: 'The engagement ring was flawless. The GIA certificate and packaging made the moment even more special.',   authorName: 'David & Amahle',  authorRole: 'Cape Town',    authorAvatar: '', rating: 5 },
          { quote: 'I wanted something uniquely South African for my 40th birthday. The rose gold bangle is absolutely perfect.', authorName: 'Bongi Khumalo',  authorRole: 'Johannesburg', authorAvatar: '', rating: 5 },
          { quote: 'The free engraving service made our anniversary gift personal in a way I didn\'t expect. She cried.',       authorName: 'Mark Ferreira',  authorRole: 'Durban',       authorAvatar: '', rating: 5 },
        ],
      },
    },
    {
      type: 'FAQAccordion',
      props: {
        id: 'FAQAccordion-jewelry-faq',
        headline: 'Questions About Our Jewellery',
        subheadline: '',
        backgroundColor: '#f9f7f4',
        cardColor: '#ffffff',
        textColor: '#1a1714',
        accentColor: '#d4af7a',
        maxWidth: 720,
        items: [
          { question: 'How do I know your gold is genuine?',             answer: 'All our gold pieces carry an official Assay Office hallmark stamped directly into the metal. We also provide a certificate of authenticity with every purchase.' },
          { question: 'Are your diamonds ethically sourced?',            answer: 'Yes. All diamonds are Kimberley Process certified and come with GIA or equivalent grading reports. We source exclusively from conflict-free mines.' },
          { question: 'Can I get a piece resized or repaired?',          answer: 'Yes — we offer ring resizing, re-rhodium plating, prong re-tipping, and chain repairs. Bring the piece in-store or contact us to arrange a postal service.' },
          { question: 'How should I care for my jewellery?',             answer: 'Store pieces individually to prevent scratching. Avoid contact with chemicals, perfume, and lotions. Clean gold with warm soapy water and a soft brush. Bring diamonds in for professional cleaning annually.' },
          { question: 'Do you offer custom or bespoke design?',          answer: 'Absolutely. We have an in-house goldsmith who works with clients on bespoke commissions — from heirloom redesigns to fully custom engagement rings. Book a consultation to discuss your vision.' },
        ],
      },
    },
    {
      type: 'NewsletterSignup',
      props: {
        id: 'NewsletterSignup-jewelry-nl',
        layout: 'banner',
        showFirstName: false,
        headline: 'Early Access to New Collections',
        subheadline: 'Be the first to see new arrivals, limited editions, and exclusive offers.',
        placeholder: 'Your email address',
        buttonText: 'Get Early Access',
        privacyText: 'We never share your details. Unsubscribe anytime.',
        successMessage: 'You\'re on the list. Look out for exclusive previews!',
        webhookUrl: '',
        accentColor: '#d4af7a',
        backgroundColor: '#1a1714',
        textColor: '#f9f7f4',
        borderRadius: 4,
      },
    },
    {
      type: 'SiteFooter',
      props: {
        id: 'SiteFooter-jewelry-ftr',
        copyrightText: '© 2025 Aurum Jewels. Fine jewellery, handcrafted in South Africa.',
        backgroundColor: '#0c0c0c',
        textColor: '#5a4e3a',
      },
    },
  ],
  zones: {},
}

// ─────────────────────────────────────────────────────────────────────────────
// Master template catalogue — ordered by tier priority
// ─────────────────────────────────────────────────────────────────────────────
export const MASTER_TEMPLATES: StoreTemplate[] = [
  // ── Tier 1 ──────────────────────────────────────────────────────────────
  {
    id: 'tmpl_fashion_v1',
    name: 'LUXE Fashion',
    category: 'fashion',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
    description: 'Dark editorial fashion store: hero banner, shop-by-collection grid, product showcase, testimonials, and newsletter.',
    tags: ['clothing', 'apparel', 'luxury', 'dark theme', 'collections'],
    puckState: fashionPuckState,
  },
  {
    id: 'tmpl_electronics_v1',
    name: 'TechVault Electronics',
    category: 'digital',
    thumbnail: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=600&q=80',
    description: 'Spec-forward tech store: hero, trending carousel, product showcase, trade-in CTA, and newsletter.',
    tags: ['electronics', 'gadgets', 'tech', 'modern', 'trade-in'],
    puckState: electronicsPuckState,
  },
  {
    id: 'tmpl_beauty_v1',
    name: 'GlowLab Beauty',
    category: 'beauty',
    thumbnail: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=600&q=80',
    description: 'Clean beauty and skincare: hero, ingredient trust badges, bestseller showcase, skin quiz CTA, reviews, FAQ, and 10% off newsletter.',
    tags: ['beauty', 'skincare', 'clean beauty', 'health', 'subscription'],
    puckState: beautyPuckState,
  },
  // ── Tier 2 ──────────────────────────────────────────────────────────────
  {
    id: 'tmpl_foodbev_v1',
    name: 'FreshBox Food & Drink',
    category: 'restaurant',
    thumbnail: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    description: 'Farm-to-table subscription box: countdown timer, 3-tier pricing table, recipe blog, FAQ, and 50% off first box offer.',
    tags: ['food', 'subscription', 'DTC', 'recipe', 'farm-to-table', 'delivery'],
    puckState: foodBevPuckState,
  },
  {
    id: 'tmpl_pet_v1',
    name: 'PawHQ Pet Supplies',
    category: 'pets',
    thumbnail: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&q=80',
    description: 'Pet food and accessories: shop-by-species grid, vet-trust feature grid, trending carousel, subscribe & save CTA, and FAQ.',
    tags: ['pets', 'dogs', 'cats', 'pet food', 'recurring', 'wellness'],
    puckState: petSuppliesPuckState,
  },
  // ── Tier 3 ──────────────────────────────────────────────────────────────
  {
    id: 'tmpl_home_v1',
    name: 'Habitat & Co. Home',
    category: 'furniture',
    thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80',
    description: 'Furniture and home goods: shop-by-room grid, quality badges, overlay product showcase, featured blog, and design consultation CTA.',
    tags: ['furniture', 'home', 'garden', 'interior', 'solid wood', 'South African'],
    puckState: homeGardenPuckState,
  },
  {
    id: 'tmpl_jewelry_v1',
    name: 'Aurum Fine Jewellery',
    category: 'fashion',
    thumbnail: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80',
    description: 'Fine jewellery with zoom gallery: dark hero, 5-column product showcase, lightbox image gallery, hallmark trust badges, and FAQ.',
    tags: ['jewellery', 'gold', 'diamonds', 'luxury', 'accessories', 'high-end'],
    puckState: jewelryPuckState,
  },
]
